#!/usr/bin/env python
"""
   Copyright 2016 The Trustees of Princeton University

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

# helper to get the list of hosts.
# used by syndicate-amd-server.

import os
import sys
import json
import socket


def TEST_get_all_hosts():
    """
    Fetch and return a list of hosts.
    Test implementation. Do not use in production.
    """
    return [socket.gethostname(), "localhost"]


def opencloud_get_all_hosts():
    """
    Fetch and return a list of hosts that are
    running instances of Syndicate gateways.
    """
    raise Exception("Opencloud support not implemented")


get_all_hosts = TEST_get_all_hosts

if __name__ == "__main__":
    """
    Get and print out a JSON document 
    with the list of hosts to query.
    """
    hosts = get_all_hosts()
    try:
        print json.dumps( hosts, indent=4, sort_keys=True )
        sys.exit(0)
    except Exception, e:
        print >> sys.stderr, "Failed to list hosts"
        sys.exit(1)


